[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]

log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1.7"
leptos = "0.2.1"
leptos_meta = "0.2.1"
leptos_router = {version="0.2.1", features = ["csr"]}


[dev-dependencies]
wasm-bindgen-test = "0.3.0"

